using System.Globalization;

namespace TokenTracker.Windows.Core;

public enum L10nKey
{
    NoUsageLoaded,
    Updated,
    Ago,
    RefreshNow,
    Preferences,
    DisplayMode,
    ProviderLabels,
    Providers,
    RefreshInterval,
    LaunchAtLogin,
    AlwaysShowIconSettings,
    Quit,
    FiveHourReset,
    SevenDayReset,
    Source,
    Error,
    Status,
    TechnicalError,
    Recovery,
    Diagnostics,
    CopyDiagnostics,
    DiagnosticsCopied,
    OpenClaudeCredentials,
    OpenCodexAuth,
    LastSuccessfulUpdate,
    NoSuccessfulUpdate,
    DuplicateInstances,
    RefreshIntervalWarning,
    Notifications,
    FiveHourAlertTitle,
    SevenDayAlertTitle,
    ResetAlertTitle,
    FiveHourAlertThreshold,
    SevenDayAlertThreshold,
    ResetAlertMinutes,
    History,
    HistoryTrend,
    NotEnoughHistory,
    ExportHistoryCsv,
    HistoryRetentionDays,
    ForecastLabel,
    ForecastBeforeReset,
    DepletionAlertTitle,
    ShowForecastLabel,
    DepletionAlertToggle,
    Plan,
    Language,
    LowestRemaining,
    Both,
    CodexOnly,
    ClaudeOnly,
    Names,
    OfficialLogos,
    TaskbarSettingsTip,
    TaskbarSettingsFallback,
    StatusEnabled,
    StatusDisabled,
    StatusOk,
    StatusOkDetail,
    StatusDisabledProvider,
    StatusDisabledProviderDetail,
    StatusRateLimited,
    StatusRateLimitedDetail,
    StatusMissingCredentials,
    StatusMissingCredentialsDetail,
    StatusInvalidResponse,
    StatusInvalidResponseDetail,
    StatusTimedOut,
    StatusTimedOutDetail,
    StatusNetworkIssue,
    StatusNetworkIssueDetail,
    StatusHttpError,
    StatusHttpErrorDetail,
    StatusUsingCachedData,
    StatusUsingCachedDataDetail,
    StatusUnavailable,
    StatusUnavailableDetail,
    RecoveryEnableProvider,
    RecoveryWaitForCooldown,
    RecoveryCheckCredentials,
    RecoveryUpdateOrTryLater,
    RecoveryCheckNetwork,
    RecoveryRefreshLater,
    RecoveryTryAgainLater
}

public sealed class Localizer
{
    public AppLanguage Language { get; }

    public Localizer(AppLanguage language)
    {
        Language = language == AppLanguage.System
            ? CultureInfo.CurrentUICulture.TwoLetterISOLanguageName.Equals("ko", StringComparison.OrdinalIgnoreCase)
                ? AppLanguage.Korean
                : AppLanguage.English
            : language;
    }

    public string Text(L10nKey key)
    {
        var table = Language == AppLanguage.Korean ? Korean : English;
        return table.TryGetValue(key, out var value) ? value : key.ToString();
    }

    public static string LanguageLabel(AppLanguage language) => language switch
    {
        AppLanguage.System => "System",
        AppLanguage.English => "English",
        AppLanguage.Korean => "한국어",
        _ => language.ToString()
    };

    private static readonly IReadOnlyDictionary<L10nKey, string> English = new Dictionary<L10nKey, string>
    {
        [L10nKey.NoUsageLoaded] = "No usage loaded yet",
        [L10nKey.Updated] = "Updated",
        [L10nKey.Ago] = "ago",
        [L10nKey.RefreshNow] = "Refresh Now",
        [L10nKey.Preferences] = "Preferences...",
        [L10nKey.DisplayMode] = "Display Mode",
        [L10nKey.ProviderLabels] = "Provider Labels",
        [L10nKey.Providers] = "Providers",
        [L10nKey.RefreshInterval] = "Refresh Interval",
        [L10nKey.LaunchAtLogin] = "Launch at Login",
        [L10nKey.AlwaysShowIconSettings] = "Always Show Icon Settings...",
        [L10nKey.Quit] = "Quit",
        [L10nKey.FiveHourReset] = "5h reset",
        [L10nKey.SevenDayReset] = "7d reset",
        [L10nKey.Source] = "Source",
        [L10nKey.Error] = "Error",
        [L10nKey.Status] = "Status",
        [L10nKey.TechnicalError] = "Technical error",
        [L10nKey.Recovery] = "Recovery",
        [L10nKey.Diagnostics] = "Diagnostics",
        [L10nKey.CopyDiagnostics] = "Copy Diagnostics",
        [L10nKey.DiagnosticsCopied] = "Diagnostics copied",
        [L10nKey.OpenClaudeCredentials] = "Open Claude Credentials",
        [L10nKey.OpenCodexAuth] = "Open Codex Auth",
        [L10nKey.LastSuccessfulUpdate] = "Last successful update",
        [L10nKey.NoSuccessfulUpdate] = "No successful update yet",
        [L10nKey.DuplicateInstances] = "Running instances",
        [L10nKey.RefreshIntervalWarning] = "Short refresh intervals can trigger provider rate limits.",
        [L10nKey.Notifications] = "Notifications",
        [L10nKey.FiveHourAlertTitle] = "5h usage is low",
        [L10nKey.SevenDayAlertTitle] = "7d usage is low",
        [L10nKey.ResetAlertTitle] = "Usage window reset soon",
        [L10nKey.FiveHourAlertThreshold] = "5h alert threshold",
        [L10nKey.SevenDayAlertThreshold] = "7d alert threshold",
        [L10nKey.ResetAlertMinutes] = "Reset alert window",
        [L10nKey.History] = "History",
        [L10nKey.HistoryTrend] = "24h trend:",
        [L10nKey.NotEnoughHistory] = "Not enough history yet",
        [L10nKey.ExportHistoryCsv] = "Export History CSV...",
        [L10nKey.HistoryRetentionDays] = "History retention",
        [L10nKey.ForecastLabel] = "Projected depletion",
        [L10nKey.ForecastBeforeReset] = "empties before reset",
        [L10nKey.DepletionAlertTitle] = "May run out before reset",
        [L10nKey.ShowForecastLabel] = "Show depletion forecast",
        [L10nKey.DepletionAlertToggle] = "Depletion alert (before reset)",
        [L10nKey.Plan] = "Plan",
        [L10nKey.Language] = "Language",
        [L10nKey.LowestRemaining] = "Lowest remaining",
        [L10nKey.Both] = "Claude + Codex",
        [L10nKey.CodexOnly] = "Codex only",
        [L10nKey.ClaudeOnly] = "Claude only",
        [L10nKey.Names] = "Names",
        [L10nKey.OfficialLogos] = "Official logos",
        [L10nKey.TaskbarSettingsTip] = "In Taskbar settings, enable Token Tracker under notification area / system tray icons.",
        [L10nKey.TaskbarSettingsFallback] = "Open Windows Settings > Personalization > Taskbar and enable Token Tracker under notification area icons.",
        [L10nKey.StatusEnabled] = "Enabled",
        [L10nKey.StatusDisabled] = "Disabled",
        [L10nKey.StatusOk] = "OK",
        [L10nKey.StatusOkDetail] = "Usage loaded normally.",
        [L10nKey.StatusDisabledProvider] = "Disabled",
        [L10nKey.StatusDisabledProviderDetail] = "This provider is turned off.",
        [L10nKey.StatusRateLimited] = "Rate limited",
        [L10nKey.StatusRateLimitedDetail] = "The provider temporarily rejected usage checks because requests were too frequent.",
        [L10nKey.StatusMissingCredentials] = "Login required",
        [L10nKey.StatusMissingCredentialsDetail] = "Token Tracker could not find local credentials for this provider.",
        [L10nKey.StatusInvalidResponse] = "Unexpected response",
        [L10nKey.StatusInvalidResponseDetail] = "The provider returned data in a format Token Tracker did not expect.",
        [L10nKey.StatusTimedOut] = "Timed out",
        [L10nKey.StatusTimedOutDetail] = "The provider did not respond before the request timed out.",
        [L10nKey.StatusNetworkIssue] = "Network issue",
        [L10nKey.StatusNetworkIssueDetail] = "The request failed before a usable provider response was received.",
        [L10nKey.StatusHttpError] = "Provider HTTP error",
        [L10nKey.StatusHttpErrorDetail] = "The provider returned an HTTP error while checking usage.",
        [L10nKey.StatusUsingCachedData] = "Using cached data",
        [L10nKey.StatusUsingCachedDataDetail] = "The latest check failed, so the last successful value is being shown.",
        [L10nKey.StatusUnavailable] = "Unavailable",
        [L10nKey.StatusUnavailableDetail] = "No usage value is currently available.",
        [L10nKey.RecoveryEnableProvider] = "Enable the provider if you want Token Tracker to check it again.",
        [L10nKey.RecoveryWaitForCooldown] = "Wait for the cooldown to pass or use a longer refresh interval.",
        [L10nKey.RecoveryCheckCredentials] = "Sign in to the provider CLI/app, then refresh Token Tracker.",
        [L10nKey.RecoveryUpdateOrTryLater] = "Try again later. If this keeps happening, update Token Tracker.",
        [L10nKey.RecoveryCheckNetwork] = "Check your network connection and try again.",
        [L10nKey.RecoveryRefreshLater] = "Refresh again later.",
        [L10nKey.RecoveryTryAgainLater] = "Try again later."
    };

    private static readonly IReadOnlyDictionary<L10nKey, string> Korean = new Dictionary<L10nKey, string>
    {
        [L10nKey.NoUsageLoaded] = "아직 사용량을 불러오지 못했습니다",
        [L10nKey.Updated] = "업데이트",
        [L10nKey.Ago] = "전",
        [L10nKey.RefreshNow] = "지금 새로고침",
        [L10nKey.Preferences] = "설정...",
        [L10nKey.DisplayMode] = "표시 방식",
        [L10nKey.ProviderLabels] = "제공자 표기",
        [L10nKey.Providers] = "제공자",
        [L10nKey.RefreshInterval] = "새로고침 주기",
        [L10nKey.LaunchAtLogin] = "로그인 시 실행",
        [L10nKey.AlwaysShowIconSettings] = "아이콘 상시 표시 설정 열기...",
        [L10nKey.Quit] = "종료",
        [L10nKey.FiveHourReset] = "5시간 리셋",
        [L10nKey.SevenDayReset] = "7일 리셋",
        [L10nKey.Source] = "데이터 출처",
        [L10nKey.Error] = "오류",
        [L10nKey.Status] = "상태",
        [L10nKey.TechnicalError] = "기술 오류",
        [L10nKey.Recovery] = "복구 방법",
        [L10nKey.Diagnostics] = "진단",
        [L10nKey.CopyDiagnostics] = "진단 정보 복사",
        [L10nKey.DiagnosticsCopied] = "진단 정보가 복사됨",
        [L10nKey.OpenClaudeCredentials] = "Claude 인증 파일 열기",
        [L10nKey.OpenCodexAuth] = "Codex 인증 파일 열기",
        [L10nKey.LastSuccessfulUpdate] = "마지막 성공 업데이트",
        [L10nKey.NoSuccessfulUpdate] = "아직 성공한 업데이트 없음",
        [L10nKey.DuplicateInstances] = "실행 중인 인스턴스",
        [L10nKey.RefreshIntervalWarning] = "짧은 새로고침 간격은 제공자 요청 제한을 유발할 수 있습니다.",
        [L10nKey.Notifications] = "알림",
        [L10nKey.FiveHourAlertTitle] = "5시간 사용량 부족",
        [L10nKey.SevenDayAlertTitle] = "7일 사용량 부족",
        [L10nKey.ResetAlertTitle] = "사용량 창 리셋 임박",
        [L10nKey.FiveHourAlertThreshold] = "5시간 알림 기준",
        [L10nKey.SevenDayAlertThreshold] = "7일 알림 기준",
        [L10nKey.ResetAlertMinutes] = "리셋 알림 시간",
        [L10nKey.History] = "히스토리",
        [L10nKey.HistoryTrend] = "24시간 추세:",
        [L10nKey.NotEnoughHistory] = "아직 히스토리가 부족합니다",
        [L10nKey.ExportHistoryCsv] = "히스토리 CSV 내보내기...",
        [L10nKey.HistoryRetentionDays] = "히스토리 보관 기간",
        [L10nKey.ForecastLabel] = "예상 소진",
        [L10nKey.ForecastBeforeReset] = "리셋 전 소진",
        [L10nKey.DepletionAlertTitle] = "리셋 전 소진 예상",
        [L10nKey.ShowForecastLabel] = "소진 예측 표시",
        [L10nKey.DepletionAlertToggle] = "소진 예측 알림 (리셋 전)",
        [L10nKey.Plan] = "플랜",
        [L10nKey.Language] = "언어",
        [L10nKey.LowestRemaining] = "가장 낮은 잔량",
        [L10nKey.Both] = "Claude + Codex",
        [L10nKey.CodexOnly] = "Codex만",
        [L10nKey.ClaudeOnly] = "Claude만",
        [L10nKey.Names] = "이름",
        [L10nKey.OfficialLogos] = "공식 로고",
        [L10nKey.TaskbarSettingsTip] = "작업표시줄 설정에서 알림 영역/시스템 트레이 아이콘 목록의 Token Tracker를 켜세요.",
        [L10nKey.TaskbarSettingsFallback] = "Windows 설정 > 개인 설정 > 작업 표시줄에서 알림 영역 아이콘의 Token Tracker를 켜세요.",
        [L10nKey.StatusEnabled] = "켜짐",
        [L10nKey.StatusDisabled] = "꺼짐",
        [L10nKey.StatusOk] = "정상",
        [L10nKey.StatusOkDetail] = "사용량을 정상적으로 불러왔습니다.",
        [L10nKey.StatusDisabledProvider] = "꺼짐",
        [L10nKey.StatusDisabledProviderDetail] = "이 제공자는 비활성화되어 있습니다.",
        [L10nKey.StatusRateLimited] = "요청 제한",
        [L10nKey.StatusRateLimitedDetail] = "요청이 너무 잦아 제공자가 사용량 확인을 일시적으로 거절했습니다.",
        [L10nKey.StatusMissingCredentials] = "로그인 필요",
        [L10nKey.StatusMissingCredentialsDetail] = "이 제공자의 로컬 인증 정보를 찾지 못했습니다.",
        [L10nKey.StatusInvalidResponse] = "예상과 다른 응답",
        [L10nKey.StatusInvalidResponseDetail] = "제공자가 Token Tracker가 예상하지 못한 형식의 데이터를 반환했습니다.",
        [L10nKey.StatusTimedOut] = "시간 초과",
        [L10nKey.StatusTimedOutDetail] = "요청 제한 시간 안에 제공자가 응답하지 않았습니다.",
        [L10nKey.StatusNetworkIssue] = "네트워크 문제",
        [L10nKey.StatusNetworkIssueDetail] = "사용 가능한 제공자 응답을 받기 전에 요청이 실패했습니다.",
        [L10nKey.StatusHttpError] = "제공자 HTTP 오류",
        [L10nKey.StatusHttpErrorDetail] = "사용량 확인 중 제공자가 HTTP 오류를 반환했습니다.",
        [L10nKey.StatusUsingCachedData] = "캐시 데이터 사용 중",
        [L10nKey.StatusUsingCachedDataDetail] = "최신 확인에 실패해 마지막 성공 값을 표시하고 있습니다.",
        [L10nKey.StatusUnavailable] = "사용 불가",
        [L10nKey.StatusUnavailableDetail] = "현재 표시할 사용량 값이 없습니다.",
        [L10nKey.RecoveryEnableProvider] = "다시 확인하려면 제공자를 켜세요.",
        [L10nKey.RecoveryWaitForCooldown] = "쿨다운이 끝날 때까지 기다리거나 새로고침 간격을 늘리세요.",
        [L10nKey.RecoveryCheckCredentials] = "제공자 CLI/앱에 로그인한 뒤 Token Tracker를 새로고침하세요.",
        [L10nKey.RecoveryUpdateOrTryLater] = "나중에 다시 시도하세요. 계속 발생하면 Token Tracker를 업데이트하세요.",
        [L10nKey.RecoveryCheckNetwork] = "네트워크 연결을 확인한 뒤 다시 시도하세요.",
        [L10nKey.RecoveryRefreshLater] = "나중에 다시 새로고침하세요.",
        [L10nKey.RecoveryTryAgainLater] = "나중에 다시 시도하세요."
    };
}
